name: derma_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  permission_handler: ^11.0.0
  google_maps_flutter: ^2.6.0
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_auth_web: ^6.1.4
  cloud_firestore_web: ^5.2.0
  speech_to_text: ^7.3.0  # أحدث نسخة متوافقة
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/DermaAi2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/mic.png
    - assets/image.jpg
    - assets/onboarding1.jpeg
    - assets/onboarding2.jpeg
    - assets/onboarding3.jpeg
    - assets/splash_capsules.jpeg
    - assets/DermaAi2.png
    - assets/upload.jpeg
    - assets/scan.jpeg
    - assets/doc1.jpeg
    - assets/doc2.jpeg
    - assets/robo.jpeg

# 👇 هذا القسم لازم يكون على نفس المستوى، مش جوه flutter
dependency_overrides:
  speech_to_text_platform_interface: 2.2.0